name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx   
      run: docker buildx install
    - name: Configure Docker Buildx
      run: docker buildx configure --use default --driver docker-container
    - name: Build the Docker image
      run: docker buildx build --file Dockerfile --platform linux/amd64 -t apisix-nonroot:latest .

